//auth
export const RESTART_AUTH_RESPONSE = 'RESTART_AUTH_RESPONSE';
export const LOADING = 'LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const CODE_ERROR = 'CODE_ERROR';
//profile
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const UPLOAD_LOADING = 'UPLOAD_LOADING'
export const UPLOAD_PROFILE_SUCCESS = 'UPLOAD_PROFILE_SUCCESS'
export const UPLOAD_PROFILE_ERROR = 'UPLOAD_PROFILE_ERROR'
export const EDIT_LOADING = 'EDIT_LOADING'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_ERROR = 'EDIT_PROFILE_ERROR'
//home
export const LOAD_HOME_HEADER = 'LOAD_HOME_HEADER'
export const LOAD_HOME_HEADER_SUCCESS = 'LOAD_HOME_HEADER_SUCCESS'
export const LOAD_HOME_HEADER_ERROR = 'LOAD_HOME_HEADER_ERROR'
export const LOAD_HOME_CARDS_SUCCESS = 'LOAD_HOME_CARDS_SUCCESS'
export const LOAD_HOME_CARDS_ERROR = 'LOAD_HOME_CARDS_ERROR'
export const LOAD_HOME_CARD = 'LOAD_HOME_CARD'
export const SHOW_HOME_CARD_SUCCESS = 'SHOW_HOME_CARD_SUCCESS'
export const SHOW_HOME_CARD_ERROR = 'SHOW_HOME_CARD_ERROR'
export const IS_EDIT_CARD = 'IS_EDIT_CARD'
export const EDIT_CARD_SUCCESS = 'EDIT_CARD_SUCCESS'
export const EDIT_CARD_ERROR = 'EDIT_CARD_ERROR'
//posts
export const IS_LOADING_POSTS = 'IS_LOADING_POSTS'
export const LOADING_POSTS_SUCCESS = 'LOADING_POSTS_SUCCESS'
export const LOADING_POSTS_ERROR = 'LOADING_POSTS_ERROR'
export const SHOW_POSTS_SUCCESS = 'SHOW_POSTS_SUCCESS'
export const SHOW_POSTS_ERROR = 'SHOW_POSTS_ERROR'
export const IS_CREATING_POST = 'IS_CREATING_POST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR'
export const IS_UPDATING_POST = 'IS_UPDATING_POST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR'
export const IS_DELETING_POST = 'IS_DELETING_POST'
export const DELETING_POST_SUCCESS = 'DELETING_POST_SUCCESS'
//chat
export const IS_FETCHING_FRIENDS = "IS_FETCHING_FRIENDS"
export const FETCH_FRIENDS = "FETCH_FRIENDS"
export const FETCH_LAST_MESSAGES = "FETCH_LAST_MESSAGES"
export const FETCH_LAST_MESSAGE_WITH = "FETCH_LAST_MESSAGE_WITH"
export const FETCH_CONVERSATION_WITH = "FETCH_CONVERSATION_WITH"
export const CACHE_CONVERSATION_WITH = "CACHE_CONVERSATION_WITH"
export const ADD_LOCAL_MSG_TO_CONVERSATION = 'ADD_LOCAL_MSG_TO_CONVERSATION'
export const SET_MESSAGE = "SET_MESSAGE"
export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID"
export const SEND_MESSAGE_TO = "SEND_MESSAGE_TO"
export const SEND_MESSAGE_TO_ERROR = "SEND_MESSAGE_TO_ERROR"
//OnlineUsers OfflineUsers
export const ONLINE_USERS = 'ONLINE_USERS'
export const OFFLINE_USERS = 'OFFLINE_USERS'
//Comments
export const IS_FETCHING_COMMENT = 'IS_FETCHING_COMMENT'
export const IS_CREATING_COMMENT = 'IS_CREATING_COMMENT'
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'
export const COMMENT_CREATED = 'COMMENT_CREATED'